// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhezhqilciiztsltljjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZXpocWlsY2lpenRzbHRsampkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDUzMDQsImV4cCI6MjA2MDgyMTMwNH0.FoCRN_LrKdwCmx16ODTLJlmnEPEgQMBWPYHykWll2jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);